version: '3.8'

services:
  dados:
    build:
      context: ./Dados
      dockerfile: dockerfile
    container_name: dados
    ports:
      - "5003:5003"
    volumes:
      - ./Dados:/app
    restart: unless-stopped

  servidor:
    build:
      context: ./servidor
      dockerfile: dockerfile
    container_name: servidor
    ports:
      - "5000:5000"
    depends_on:
      - dados
    volumes:
      - ./servidor:/app
    restart: unless-stopped

  cliente:
    build:
      context: ./cliente
      dockerfile: dockerfile
    container_name: cliente
    depends_on:
      - servidor
    volumes:
      - ./cliente:/app
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    restart: unless-stopped
    # Para rodar GUI, precisa do X11 forwarding habilitado no host

networks:
  beco-diagonal-network:
    driver: bridge
