# Use uma imagem base do Python
FROM python:3.9-slim

# Crie e defina o diretório de trabalho dentro do container
WORKDIR /app

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    libx11-dev \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libxkbcommon0 \
    libegl1

# Copie os arquivos de dependência (caso haja um requirements.txt)
COPY requirements.txt /app/

# Instale as dependências do cliente
RUN pip install --no-cache-dir -r requirements.txt

# Copie o restante dos arquivos do projeto para o container
COPY . /app/

# Exponha a porta que o cliente pode precisar
EXPOSE 5000

# Comando para rodar o cliente
CMD ["python", "clienteGUI.py"]
