# Usa uma imagem oficial do Python como base
FROM python:3.10-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos do projeto para dentro do contêiner
COPY . .

# Expõe a porta usada pelo servidor (ajuste se necessário)
EXPOSE 5000

# Comando para rodar o servidor
CMD ["python", "servidor_mock.py"]
